In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')

In [3]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
#preprocessing

data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
#encode one categorical data

label_encoder=LabelEncoder()
data['Gender']=label_encoder.fit_transform(data['Gender'])

In [7]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [8]:
#onehot ecoding for geo

from sklearn.preprocessing import OneHotEncoder
onehotgeo=OneHotEncoder()
data_geo=onehotgeo.fit_transform(data[['Geography']])
data_geo

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [9]:
onehotgeo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [10]:
geo_encodeed_pd=pd.DataFrame(data_geo.toarray(), columns=onehotgeo.get_feature_names_out(['Geography']))
geo_encodeed_pd

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [11]:
##combines columns 

data=pd.concat([data.drop('Geography',axis=1),geo_encodeed_pd],axis=1)

In [12]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [16]:
#save the encode adn scaler




with open('label_encoder.pkl','wb') as f:
    pickle.dump(label_encoder,f)

with open('onehot_encoder_geography.pkl','wb') as f:
    pickle.dump(onehotgeo,f)

In [17]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [18]:
#divide data into dep. and indep 

x=data.drop('Exited',axis=1)
y=data['Exited']

#split data into train and test


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)


##scalling these features

scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [19]:
x_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(8000, 12))

In [20]:
x_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(2000, 12))

In [21]:
with open('scaler.pkl','wb') as f:
    pickle.dump(scaler,f)

In [22]:
print("Load tge picle file ")

Load tge picle file

In [ ]:
##Ann implementation

In [32]:
pip install tensorboard

Collecting tensorboard
  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: absl-py>=0.4 in /opt/anaconda3/envs/tf_env/lib/python3.10/site-packages (from tensorboard) (2.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /opt/anaconda3/envs/tf_env/lib/python3.10/site-packages (from tensorboard) (1.80.0)
Collecting markdown>=2.6.8 (from tensorboard)
  Using cached markdown-3.10.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: numpy>=1.12.0 in /opt/anaconda3/envs/tf_env/lib/python3.10/site-packages (from tensorboard) (2.2.6)
Requirement already satisfied: packaging in /opt/anaconda3/envs/tf_env/lib/python3.10/site-packages (from tensorboard) (26.0)
Collecting pillow (from tensorboard)
  Using cached pillow-12.2.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (8.8 kB)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /opt/anaconda3/envs/tf_env/lib/python3.10/site-packages (from tensorboard) (7.34.1)
Requirement already satisfied: setuptools>=41.0.0 in /opt/anaconda3/envs/tf_env/lib/python3.10/site-packages (from tensorboard) (82.0.1)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard)
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard)
  Using cached werkzeug-3.1.8-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: typing-extensions~=4.12 in /opt/anaconda3/envs/tf_env/lib/python3.10/site-packages (from grpcio>=1.48.2->tensorboard) (4.15.0)
Requirement already satisfied: markupsafe>=2.1.1 in /opt/anaconda3/envs/tf_env/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Using cached tensorboard-2.20.0-py3-none-any.whl (5.5 MB)
Using cached tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Using cached markdown-3.10.2-py3-none-any.whl (108 kB)
Using cached werkzeug-3.1.8-py3-none-any.whl (226 kB)
Using cached pillow-12.2.0-cp310-cp310-macosx_11_0_arm64.whl (4.7 MB)
Installing collected packages: werkzeug, tensorboard-data-server, pillow, markdown, tensorboard
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [tensorboard] [tensorboard]
Successfully installed markdown-3.10.2 pillow-12.2.0 tensorboard-2.20.0 tensorboard-data-server-0.7.2 werkzeug-3.1.8
Note: you may need to restart the kernel to use updated packages.

In [37]:
pip install --upgrade setuptools

Requirement already satisfied: setuptools in /opt/anaconda3/envs/tf_env/lib/python3.10/site-packages (82.0.1)
Note: you may need to restart the kernel to use updated packages.

In [23]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [24]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)), #only written fro first layer as it is input layer
    Dropout(0.5),
    Dense(32,activation='relu'),
    Dropout(0.5),
    Dense(16,activation='relu'),
    Dropout(0.5),
    Dense(1,activation='sigmoid')
])

/opt/anaconda3/envs/tf_env/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [25]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,457 (13.50 KB)

 Trainable params: 3,457 (13.50 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
##compile the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [27]:
opt=tf.keras.optimizers.Adam(learning_rate=0.001)
loss=tf.keras.losses.BinaryCrossentropy()
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

In [28]:
#set up tensorboard

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [29]:
tensorboard_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [30]:
##early stopping

early_stopping=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [33]:
##training the model

history=model.fit(
    x_train,y_train,
    validation_data=(x_test,y_test),
    epochs=100,
    batch_size=32,
    callbacks=[early_stopping,tensorboard_callback] 
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6967 - loss: 0.6100 - val_accuracy: 0.8035 - val_loss: 0.4645
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 768us/step - accuracy: 0.7936 - loss: 0.5076 - val_accuracy: 0.8035 - val_loss: 0.4313
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step - accuracy: 0.7972 - loss: 0.4792 - val_accuracy: 0.8040 - val_loss: 0.4191
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step - accuracy: 0.8011 - loss: 0.4705 - val_accuracy: 0.8055 - val_loss: 0.4127
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 771us/step - accuracy: 0.8070 - loss: 0.4616 - val_accuracy: 0.8160 - val_loss: 0.4124
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 745us/step - accuracy: 0.8034 - loss: 0.4520 - val_accuracy: 0.8110 - val_loss: 0.4032
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - accuracy: 0.8041 - loss: 0.4453 - val_accuracy: 0.8115 - val_loss: 0.3976
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 792us/step - accuracy: 0.8121 - loss: 0.4337 - val_accuracy: 0.8250 - val_loss: 0.3895
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 750us/step - accuracy: 0.8167 - loss: 0.4291 - val_accuracy: 0.8365 - val_loss: 0.3778
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.8207 - loss: 0.4234 - val_accuracy: 0.8420 - val_loss: 0.3744
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step - accuracy: 0.8217 - loss: 0.4135 - val_accuracy: 0.8500 - val_loss: 0.3679
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.8259 - loss: 0.4107 - val_accuracy: 0.8505 - val_loss: 0.3632
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.8289 - loss: 0.4046 - val_accuracy: 0.8480 - val_loss: 0.3595
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.8299 - loss: 0.3997 - val_accuracy: 0.8520 - val_loss: 0.3537
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 797us/step - accuracy: 0.8322 - loss: 0.3956 - val_accuracy: 0.8510 - val_loss: 0.3573
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.8361 - loss: 0.3932 - val_accuracy: 0.8565 - val_loss: 0.3526
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 797us/step - accuracy: 0.8360 - loss: 0.3869 - val_accuracy: 0.8535 - val_loss: 0.3512
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 782us/step - accuracy: 0.8405 - loss: 0.3875 - val_accuracy: 0.8545 - val_loss: 0.3505
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 754us/step - accuracy: 0.8397 - loss: 0.3906 - val_accuracy: 0.8535 - val_loss: 0.3513
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 745us/step - accuracy: 0.8403 - loss: 0.3831 - val_accuracy: 0.8555 - val_loss: 0.3471
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 751us/step - accuracy: 0.8429 - loss: 0.3821 - val_accuracy: 0.8550 - val_loss: 0.3500
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 767us/step - accuracy: 0.8451 - loss: 0.3769 - val_accuracy: 0.8540 - val_loss: 0.3488
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 749us/step - accuracy: 0.8424 - loss: 0.3761 - val_accuracy: 0.8560 - val_loss: 0.3458
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step - accuracy: 0.8432 - loss: 0.3767 - val_accuracy: 0.8545 - val_loss: 0.3489
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step - accuracy: 0.8454 - loss: 0.3783 - val_accuracy: 0.8560 - val_loss: 0.3457
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8446 - loss: 0.3776 - val_accuracy: 0.8555 - val_loss: 0.3444
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 752us/step - accuracy: 0.8441 - loss: 0.3747 - val_accuracy: 0.8550 - val_loss: 0.3434
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - accuracy: 0.8446 - loss: 0.3759 - val_accuracy: 0.8585 - val_loss: 0.3469
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 751us/step - accuracy: 0.8501 - loss: 0.3682 - val_accuracy: 0.8565 - val_loss: 0.3459
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 775us/step - accuracy: 0.8450 - loss: 0.3739 - val_accuracy: 0.8565 - val_loss: 0.3430
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 752us/step - accuracy: 0.8506 - loss: 0.3702 - val_accuracy: 0.8575 - val_loss: 0.3428
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 749us/step - accuracy: 0.8491 - loss: 0.3690 - val_accuracy: 0.8570 - val_loss: 0.3418
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 750us/step - accuracy: 0.8535 - loss: 0.3660 - val_accuracy: 0.8560 - val_loss: 0.3406
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 760us/step - accuracy: 0.8526 - loss: 0.3662 - val_accuracy: 0.8535 - val_loss: 0.3423
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 779us/step - accuracy: 0.8499 - loss: 0.3642 - val_accuracy: 0.8575 - val_loss: 0.3399
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 762us/step - accuracy: 0.8493 - loss: 0.3680 - val_accuracy: 0.8560 - val_loss: 0.3414
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 751us/step - accuracy: 0.8470 - loss: 0.3672 - val_accuracy: 0.8590 - val_loss: 0.3406
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.8505 - loss: 0.3658 - val_accuracy: 0.8545 - val_loss: 0.3416
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 769us/step - accuracy: 0.8521 - loss: 0.3663 - val_accuracy: 0.8585 - val_loss: 0.3387
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 751us/step - accuracy: 0.8512 - loss: 0.3600 - val_accuracy: 0.8565 - val_loss: 0.3427
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step - accuracy: 0.8528 - loss: 0.3620 - val_accuracy: 0.8590 - val_loss: 0.3379
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 747us/step - accuracy: 0.8544 - loss: 0.3588 - val_accuracy: 0.8565 - val_loss: 0.3357
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 742us/step - accuracy: 0.8543 - loss: 0.3595 - val_accuracy: 0.8570 - val_loss: 0.3407
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 752us/step - accuracy: 0.8508 - loss: 0.3663 - val_accuracy: 0.8560 - val_loss: 0.3397
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.8543 - loss: 0.3583 - val_accuracy: 0.8590 - val_loss: 0.3385
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 765us/step - accuracy: 0.8533 - loss: 0.3631 - val_accuracy: 0.8595 - val_loss: 0.3407
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 753us/step - accuracy: 0.8508 - loss: 0.3641 - val_accuracy: 0.8560 - val_loss: 0.3393

In [34]:
model.save("model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [41]:
pip install --upgrade --force-reinstall setuptools

Collecting setuptools
  Using cached setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Using cached setuptools-82.0.1-py3-none-any.whl (1.0 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 82.0.1
    Uninstalling setuptools-82.0.1:
      Successfully uninstalled setuptools-82.0.1
Successfully installed setuptools-82.0.1
Note: you may need to restart the kernel to use updated packages.

In [53]:
tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 48163), started 0:01:46 ago. (Use '!kill 48163' to kill it.)

In [46]:
#load tensorboard extension 

%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [52]:
%tensorboard --logdir logs/fit/20260418-005504

Reusing TensorBoard on port 6007 (pid 48265), started 0:00:32 ago. (Use '!kill 48265' to kill it.)

In [48]:
pip install setuptools

Requirement already satisfied: setuptools in /opt/anaconda3/envs/tf_env/lib/python3.10/site-packages (82.0.1)
Note: you may need to restart the kernel to use updated packages.